apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: linkding
  name: linkding
  namespace: linkding
spec:
  replicas: 2
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:
      containers:
      - image: sissbruecker/linkding:1.36.0
        name: linkding
        volumeMounts:
        - mountPath: "/linkding"
          name: linkding-pv 
        ports:
        - containerPort: 9090
      volumes:
      - name: linkding-pv
        persistentVolumeClaim:
          claimName: linkding-claim
