apiVersion: v1
kind: PersistentVolume
metadata:
  name: linkding-pv
  namespace: linkding
spec:
  capacity:
    storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-path
  hostPath:
    path: /linkding
