apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: linkding
  name: linkding
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: linkding
  type: LoadBalancer
status:
  loadBalancer: {}
