apiVersion: v1
kind: Pod
metadata:
  name: nginx-pd
spec:
  containers:
  - image: nginx
    name: webserver
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  volumes:
  - name: cache-volume
    emptyDir:
      sizeLimit: 500Mi
