# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: littlelink
  namespace: littlelink 
  labels:
    app: littlelink
spec:
  selector:
    matchLabels:
      app: littlelink
  replicas: 1
  template:
    metadata:
      labels:
        app: littlelink
    spec:
      containers:
      - name: littlelink
        image: ghcr.io/techno-tim/littlelink-server:latest
        env:
          - name: META_TITLE
            value: 'Diogo Guedes'
          - name: META_DESCRIPTION
            value: 'DevOps Engineer'
          - name: META_AUTHOR
            value: 'Diogo Guedes'
          - name: META_KEYWORDS
            value: 'DevOps, Cloud, Engineering, Automation'
          - name: LANG
            value: 'en'
          - name: META_INDEX_STATUS
            value: 'all'
          - name: OG_SITE_NAME
            value: 'Diogo Guedes'
          - name: OG_TITLE
            value: 'Diogo Guedes'
          - name: OG_DESCRIPTION
            value: 'The home of Diogo Guedes'
          - name: OG_URL
            value: 'CHANGEME'
          - name: OG_IMAGE
            value: 'https://yourimageurl.com/profile.jpg'
          - name: OG_IMAGE_WIDTH
            value: '400'
          - name: OG_IMAGE_HEIGHT
            value: '400'
          - name: THEME
            value: 'Dark'
          - name: AVATAR_URL
            value: 'https://avatars.githubusercontent.com/u/45937530?v=4'
          - name: AVATAR_ALT
            value: 'Diogo Guedes Profile Pic'
          - name: NAME
            value: 'Diogo Guedes'
          - name: BIO
            value: 'DevOps Engineer | Cloud Enthusiast | Automation Advocate'
          - name: BUTTON_ORDER
            value: 'GITHUB,LINKED_IN,GEAR,DOCUMENTATION'
          - name: CUSTOM_BUTTON_TEXT
            value: 'Documentation,Recommended Gear'
          - name: CUSTOM_BUTTON_URL
            value: 'https://diogoguedes.dev/docs,https://diogoguedes.dev/gear'
          - name: CUSTOM_BUTTON_COLOR
            value: '#000000,#000000'
          - name: CUSTOM_BUTTON_TEXT_COLOR
            value: '#ffffff,#ffffff'
          - name: CUSTOM_BUTTON_ALT_TEXT
            value: 'Documentation for my projects,Recommended Gear'
          - name: CUSTOM_BUTTON_NAME
            value: 'DOCUMENTATION,GEAR'
          - name: CUSTOM_BUTTON_ICON
            value: 'fas fa-file-alt,fas fa-cog'
          - name: GITHUB
            value: 'https://github.com/diogoguedes11'
          - name: LINKED_IN
            value: 'https://www.linkedin.com/in/diogo-guedes11/'
          - name: FOOTER
            value: 'Diogo Guedes © 2025'
        ports:
        - containerPort: 3000
          name: littlelink
---

