apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: homepage
  name: homepage
  namespace: homepage
spec:
  replicas: 2
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
      - image: ghcr.io/gethomepage/homepage:latest
        name: homepage
        volumeMounts:
        - mountPath: "/app/config"
          name: homepage-storage
        ports:
        - containerPort: 3000
      volumes:
      - name: homepage-storage
        persistentVolumeClaim:
          claimName: homepage-data

