apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homepage-data
  namespace: homepage
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

