name: Call docker custom action
on: [workflow_dispatch]
jobs:
  docker-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: call docker action
        uses: './.github/actions/my-docker-gh'  
        with:
          who-to-greet: 'Diogo'