name: Use my github action
on: [workflow_dispatch]
jobs:
  run-custom-gh-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Deploy my custom GH action
        uses: './.github/actions/my-custom-gh'
        with:
          who-to-greet: "Maria"

