name: Messenger Workflow
on: [workflow_dispatch]
jobs:
  lets-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Debug msg
        run: | 
          echo "::debug::Hello Debug message"
      - name: Notice msg
        run: |
          echo "::notice::Hello Notice message"
      - name: Warning msg
        run: |
          echo "::warning::Hello Warning message"
      - name: Group msg
        run: |
          echo "::group::My title"
          echo "Inside the group"
          echo "::endgroup::"
      - name: My password
        run: | 
          echo '::add-mask::test'
          echo This is a test             