name: Java CI with Maven
env:
  NAME: ‘My Action‘
on:
  workflow_dispatch:
jobs:
  build:
    env:
      NAME: 'My Action 2'
    runs-on: ubuntu-latest
    steps:
    - name: ${{ 'name'}}
      run: echo "$NAME"
      env:
        NAME: 'My Action 3'